/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { render } from "@testing-library/react-native";
import AuthScreen from "../AuthScreen";

describe("AuthScreen", () => {
  it("renders correctly", () => {
    const { getByText } = render(<AuthScreen />);

    expect(getByText("Sign in with Coinbase")).toBeTruthy();
    expect(getByText("Connect MetaMask Wallet")).toBeTruthy();
    expect(getByText("or")).toBeTruthy();
    expect(
      getByText("Need help? Learn more about how to connect.")
    ).toBeTruthy();
  });
});
