/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { View, Image, StyleSheet } from "react-native";
import { YStack, XStack, Button, Text } from "tamagui";
import ConnectButton from "./ConnectButton";





const AuthScreen: React.FC = () => {
  return (
    <YStack style={styles.container}>
      <XStack style={styles.header} justifyContent="space-between">
        <Image
          resizeMode="contain"
          source={{ uri: './assets/images/icon.png'}}
          style={styles.logo}
        />
        <Image
          resizeMode="contain"
          source={{ uri: './assets/images/icon.png'}}
          style={styles.secondaryLogo}
        />
      </XStack>
      <Image
        resizeMode="contain"
        source={{ uri: './assets/images/icon.png'}}
        style={styles.mainImage}
      />
      <ConnectButton text="Sign in with Coinbase" variant="filled" />
      <ConnectButton text="Connect MetaMask Wallet" variant="outlined" />
      <Text style={styles.orText}>or</Text>
      <Text style={styles.helpText}>
        Need help? Learn more about how to connect.
      </Text>
      <View style={styles.footer} />
    </YStack>
  );
};

const styles = StyleSheet.create({
  container: {
    backgroundColor: "rgba(255, 255, 255, 1)",
    maxWidth: 480,
    width: "100%",
    alignItems: "center",
    margin: "auto",
    padding: 21,
  },
  header: {
    alignSelf: "stretch",
    gap: 20,
    overflow: "hidden",
  },
  logo: {
    borderRadius: 32,
    width: 54,
    aspectRatio: 2.57,
  },
  secondaryLogo: {
    width: 66,
    aspectRatio: 5.49,
  },
  mainImage: {
    borderRadius: 10,
    marginTop: 135,
    width: 170,
    maxWidth: "100%",
    aspectRatio: 1.08,
  },
  orText: {
    color: "#14304A",
    textAlign: "center",
    letterSpacing: 0.06,
    marginTop: 16,
    fontSize: 11,
  },
  helpText: {
    color: "#14304A",
    textAlign: "center",
    letterSpacing: 0.06,
    marginTop: 16,
    fontSize: 11,
  },
  footer: {
    borderRadius: 100,
    backgroundColor: "#191052",
    marginTop: 229,
    width: 134,
    height: 5,
  },
});

export default AuthScreen;
