/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { Button } from "tamagui";

interface ConnectButtonProps {
  text: string;
  variant: "filled" | "outlined";
}

const ConnectButton: React.FC<ConnectButtonProps> = ({ text, variant }) => {
  return (
    <Button
      size="$4"
      theme={variant === "filled" ? "dark" : "light"}
      variant={variant === "filled" ? undefined : "outlined"}
      marginTop={variant === "filled" ? 53 : 16}
    >
      {text}
    </Button>
  );
};

export default ConnectButton;
